(() => {
"use strict";
const CFG=window.VELHO_CONFIG||{}, API=(CFG.API_URL||"").replace(/\/$/,"");
let token=localStorage.getItem("uv_token")||"", me=JSON.parse(localStorage.getItem("uv_me")||"null"), socket=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function save(){localStorage.setItem("uv_token",token);localStorage.setItem("uv_me",JSON.stringify(me))}
function clear(){localStorage.removeItem("uv_token");localStorage.removeItem("uv_me");token="";me=null}
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",...(opts.headers||{}),...(token?{"Authorization":"Bearer "+token}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Erro de comunicação");return d}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function panel(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function close(){ $("#modal").classList.add("hidden") }
function setPlatform(mode){const p=mode==="mobile"?"mobile":"desktop";document.body.classList.remove("platform-mobile","platform-desktop");document.body.classList.add("platform-"+p);localStorage.setItem("uv_platform",p);$("#platformGate")?.remove();window.VELHO_PLATFORM=p}
function initPlatform(){const gate=$("#platformGate");if(!gate)return;const saved=localStorage.getItem("uv_platform");if(saved){setPlatform(saved);return}gate.querySelectorAll("[data-platform]").forEach(b=>b.onclick=()=>setPlatform(b.dataset.platform));$("#autoPlatform").onclick=()=>setPlatform(/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||matchMedia("(max-width:760px)").matches?"mobile":"desktop")}
function connect(){if(!token||!window.io)return;socket=io(API||undefined,{auth:{token},transports:["websocket","polling"]});socket.on("connect",()=>{$("#status").textContent="🟢 online";refreshStats()});socket.on("disconnect",()=>$("#status").textContent="🔴 offline");socket.on("connect_error",()=>$("#status").textContent="🟠 erro");socket.on("uno:freeze",d=>{toast("⛔ "+(d?.message||"Jogo congelado pelo administrador"));document.body.classList.add("game-frozen")});socket.on("uno:unfreeze",()=>{toast("✅ Jogo descongelado");document.body.classList.remove("game-frozen")});}
function enter(){if(!me)return;$("#intro").classList.add("hidden");$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");$("#me").textContent=me.display_name||me.username;$("#admin").classList.toggle("hidden",!me.is_admin);connect();refreshStats()}
async function login(u,p){const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({username:u,password:p})});token=d.token;me=d.user;save();enter()}
async function register(u,n,p){const d=await api("/api/auth/register",{method:"POST",body:JSON.stringify({username:u,display_name:n,password:p})});token=d.token;me=d.user;save();enter()}
async function safeApi(path,opts={},fallback){try{return await api(path,opts)}catch(e){if(fallback!==undefined)return fallback;throw e}}
async function refreshStats(){const d=await safeApi("/api/rooms",{method:"GET"},null);if(d?.rooms)$("#roomCount").textContent=d.rooms.length;const p=await safeApi("/api/online",{method:"GET"},null);if(p?.players)$("#onlineCount").textContent=p.players.length;measurePing()}
async function measurePing(){const t=performance.now();try{await fetch((API||"")+"/health",{cache:"no-store"});$("#ping").textContent=Math.round(performance.now()-t)}catch{$("#ping").textContent="--"}}
function fpsMeter(){let frames=0,last=performance.now();function f(now){frames++;if(now-last>=1000){$("#fps").textContent=frames;frames=0;last=now}requestAnimationFrame(f)}requestAnimationFrame(f)}
async function introThenAuth(){if(token){try{const d=await api("/api/auth/me");me=d.user;save();setTimeout(enter,3900);return}catch{clear()}}setTimeout(()=>{$("#intro").classList.add("hidden");$("#auth").classList.remove("hidden")},4000)}

function onlinePanel(){
panel(`<h2>🌐 Jogar Online</h2><p>Partidas com <b>mínimo de 2 jogadores</b>, porta de 4 caracteres e opção de espectador.</p>
<div class="card-grid"><button id="createRoom">🚪 Criar porta</button><button id="joinRoom">🔑 Entrar em porta</button><button id="publicRooms">🌎 Salas públicas</button><button id="spectate">👁️ Espectador</button></div><div id="onlineArea" class="cmd">Escolha uma opção.</div>`);
$("#createRoom").onclick=()=>roomCreateUI();$("#joinRoom").onclick=()=>roomJoinUI();$("#publicRooms").onclick=()=>roomsUI();$("#spectate").onclick=()=>spectateUI()
}
function roomCreateUI(){panel(`<h2>🚪 Criar porta</h2><div class="card-grid">
<div><label>Nome da sala<input id="roomName" class="control-input" maxlength="30" placeholder="Mesa do Velho"></label></div>
<div><label>Mapa<select id="map" class="control-select"><option>Taberna Medieval</option><option>Salão Neon</option><option>Biblioteca Antiga</option><option>Praia ao Entardecer</option><option>Floresta Mística</option><option>Estação Espacial</option><option>Castelo</option><option>Deserto</option><option>Arcade</option><option>Templo</option></select></label></div>
<div><label>Máximo de jogadores<select id="maxPlayers" class="control-select"><option>2</option><option selected>4</option><option>6</option><option>8</option></select></label></div>
<div><label>Cartas especiais<select id="specials" class="control-select"><option>Normal</option><option>Troca cartas</option><option>Sem +4</option><option>Sem +2</option><option>Escolha do jogador</option></select></label></div>
</div><button class="primary" id="doCreate">CRIAR PORTA</button><div id="roomResult"></div>`);
$("#doCreate").onclick=async()=>{try{const d=await api("/api/rooms",{method:"POST",body:JSON.stringify({name:$("#roomName").value.trim()||"Mesa do Velho",map:$("#map").value,max_players:+$("#maxPlayers").value,special_rules:$("#specials").value,public:true})});$("#roomResult").innerHTML=`<div class="cmd">Porta criada: <b>${esc(d.room?.code||d.code||"----")}</b><br>Compartilhe a porta com os jogadores.</div>`;refreshStats()}catch(e){$("#roomResult").innerHTML=`<div class="cmd">${esc(e.message)}</div>`}}
}
function roomJoinUI(){panel(`<h2>🔑 Entrar em porta</h2><input id="roomCode" class="control-input" maxlength="4" minlength="4" placeholder="AB12" style="text-transform:uppercase"><button class="primary" id="doJoin">ENTRAR</button><div id="joinResult"></div>`);$("#doJoin").onclick=async()=>{const code=$("#roomCode").value.trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code))return toast("A porta precisa ter 4 caracteres.");try{await api("/api/rooms/"+encodeURIComponent(code)+"/join",{method:"POST"});$("#joinResult").innerHTML="<div class='cmd success'>Entrada autorizada.</div>"}catch(e){$("#joinResult").innerHTML=`<div class="cmd">${esc(e.message)}</div>`}}}
async function roomsUI(){panel("<h2>🌎 Salas públicas</h2><div id='roomsList'>Carregando...</div>");try{const d=await api("/api/rooms");$("#roomsList").innerHTML=(d.rooms||[]).map(r=>`<div class="room-row"><span><b>${esc(r.name)}</b><br><small>${esc(r.map)} • ${r.players||0}/${r.max_players}</small></span><button data-room="${esc(r.code)}">ENTRAR</button></div>`).join("")||"<p>Nenhuma sala aberta.</p>";$$("[data-room]").forEach(b=>b.onclick=async()=>{try{await api("/api/rooms/"+b.dataset.room+"/join",{method:"POST"});toast("Entrou na sala.");close()}catch(e){toast(e.message)}})}catch(e){$("#roomsList").innerHTML=`<div class='cmd'>${esc(e.message)}</div>`}}
function spectateUI(){roomsUI()}
function soloPanel(){panel(`<h2>🤖 Solo</h2><p>Treinamento ou partida contra máquina.</p><div class="card-grid"><button>🎓 Treinamento</button><button>🤖 Contra máquina</button></div><div class="cmd">Modo solo pode funcionar sem servidor; o multiplayer usa a API configurada.</div>`)}
function shopPanel(){panel(`<h2>🛒 Loja</h2><p>Itens leves: o cliente guarda apenas IDs/cores; arquivos pesados devem ficar em CDN/servidor.</p><div class="card-grid"><button>🧑 Skins</button><button>👕 Roupas</button><button>💇 Cabelos</button><button>✨ Acessórios</button></div>`)}
function characterPanel(){panel(`<h2>🧑 Seu personagem</h2><p>Avatar de peito para cima, com rosto, olhos, cabelo, cores e acessórios.</p><div class="card-grid"><button>👤 Rosto</button><button>👁️ Cor dos olhos</button><button>💇 Cabelo</button><button>🎩 Acessório</button><button>👕 Roupa</button><button>🎨 Cor da pele/roupa</button></div>`)}
function settingsPanel(){panel(`<h2>⚙️ Configurações</h2><div class="card-grid"><button id="musicToggle">🎵 Música: ${localStorage.getItem("uv_music")!=="off"?"ON":"OFF"}</button><button id="soundToggle">🔊 Som: ${localStorage.getItem("uv_sound")!=="off"?"ON":"OFF"}</button><button id="graphics">🎮 Gráficos: ${localStorage.getItem("uv_graphics")||"médio"}</button><button id="brightness">☀️ Brilho: ${localStorage.getItem("uv_brightness")||"100"}%</button></div><div class="cmd">FPS: ${$("#fps").textContent} | Ping: ${$("#ping").textContent} ms<br>Essas preferências ficam no aparelho e não pesam no banco.</div>`);
$("#musicToggle").onclick=()=>{const v=localStorage.getItem("uv_music")==="off"?"on":"off";localStorage.setItem("uv_music",v);settingsPanel()};$("#soundToggle").onclick=()=>{const v=localStorage.getItem("uv_sound")==="off"?"on":"off";localStorage.setItem("uv_sound",v);settingsPanel()};$("#graphics").onclick=()=>{const a=["baixo","médio","alto"],c=localStorage.getItem("uv_graphics")||"médio",n=a[(a.indexOf(c)+1)%a.length];localStorage.setItem("uv_graphics",n);settingsPanel()};$("#brightness").onclick=()=>{let n=+(localStorage.getItem("uv_brightness")||100);n=n>=100?60:n+20;localStorage.setItem("uv_brightness",n);document.documentElement.style.filter=`brightness(${n/100})`;settingsPanel()}
}
async function ranking(){try{const d=await api("/api/ranking");panel("<h2>🏆 Pódio</h2>"+(d.ranking||[]).map((x,i)=>`<div class="cmd">#${i+1} — ${esc(x.display_name)} · ${x.wins} vitórias · ${x.points} pontos</div>`).join("")||"<p>Sem jogadores.</p>")}catch(e){panel(`<h2>🏆 Pódio</h2><div class="cmd">${esc(e.message)}</div>`)}}

const commands=[
["/all","lista jogadores online + ID"],["/criar staff","cria conta com permissões de Staff"],["/criar skin","cria skin"],["/mudar loja","altera itens e preços"],["/renunciarpódio","reinicia o pódio"],["/help","mostra esta lista"],["/banir id","baniu jogador pelo ID"],["/expulsar id","expulsa jogador da partida"],["/ver partida","lista partidas abertas"],["/chatglobal on/off","liga/desliga chat global"],["/chat on/off","liga/desliga chat privado"],["/congelar msg: texto","congela jogo e mostra mensagem"],["/descongelar","retoma o jogo"],["/criarmapa","cria mapa/mesa personalizada"],["/presente id","envia presente ao jogador"],["/espectar id","entra como espectador"],["/reiniciarpodio","reinicia pódio"],["/partida id","administra uma partida"]];

function adminPanel(){panel(`<h2>👑 Central do Velho</h2><p>Comandos exclusivos do administrador. Ações reais dependem da API do servidor.</p><div class="card-grid">${commands.map(c=>`<button data-cmd="${esc(c[0])}"><b>${esc(c[0])}</b><br><small>${esc(c[1])}</small></button>`).join("")}</div><div style="margin-top:15px"><input id="commandInput" class="control-input" placeholder="/help"><button class="primary" id="runCommand">EXECUTAR COMANDO</button></div><div id="adminOutput" class="cmd"><b>Velho &gt;</b> /help</div>`);
$$("[data-cmd]").forEach(b=>b.onclick=()=>{$("#commandInput").value=b.dataset.cmd;runAdminCommand()});$("#runCommand").onclick=runAdminCommand}
async function runAdminCommand(){const input=$("#commandInput").value.trim();if(!input)return;const out=$("#adminOutput");if(input==="/help"){out.innerHTML=commands.map(c=>`<b>${esc(c[0])}</b> — ${esc(c[1])}`).join("\n");return}try{const d=await api("/api/admin/command",{method:"POST",body:JSON.stringify({command:input})});out.textContent=d.message||d.result||"Comando executado."}catch(e){out.textContent=e.message}}
function bind(){ $$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#loginForm").classList.toggle("hidden",b.dataset.tab!=="login");$("#registerForm").classList.toggle("hidden",b.dataset.tab!=="register");$("#authMsg").textContent=""});
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#authMsg").textContent="Entrando...";try{await login($("#loginUser").value.trim(),$("#loginPass").value)}catch(x){$("#authMsg").textContent=x.message}};
$("#registerForm").onsubmit=async e=>{e.preventDefault();$("#authMsg").textContent="Criando conta...";try{await register($("#regUser").value.trim(),$("#regName").value.trim(),$("#regPass").value)}catch(x){$("#authMsg").textContent=x.message}};
$("#logout").onclick=()=>{socket?.disconnect();clear();location.reload()};$("#close").onclick=close;
$("#online").onclick=onlinePanel;$("#solo").onclick=soloPanel;$("#shop").onclick=shopPanel;$("#character").onclick=characterPanel;$("#settings").onclick=settingsPanel;$("#ranking").onclick=ranking;$("#adminBtn").onclick=adminPanel}
initPlatform();bind();fpsMeter();introThenAuth();
})();